# permissions for end users to edit vineyardjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vineyardjob-editor-role
rules:
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardjobs/status
  verbs:
  - get
