# permissions for end users to view vineyardjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vineyardjob-viewer-role
rules:
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardjobs/status
  verbs:
  - get
