apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: machine-learning-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0, pipelines.kubeflow.org/pipeline_compilation_time: '2023-09-13T13:57:48.817920',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example pipeline that
      trains and logs a regression model.", "name": "Machine Learning Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0}
spec:
  entrypoint: machine-learning-pipeline
  templates:
  - name: machine-learning-pipeline
    dag:
      tasks:
      - {name: preprocess-data, template: preprocess-data}
      - name: test-data
        template: test-data
        dependencies: [train-data]
      - name: train-data
        template: train-data
        dependencies: [preprocess-data]
  - name: preprocess-data
    container:
      command: [python3, preprocess.py]
      image: preprocess-data
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
      - name: DATA_MULTIPLIER
        value: "{{workflow.parameters.data_multiplier}}"
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: test-data
    container:
      command: [python3, test.py]
      image: test-data
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
      - name: DATA_MULTIPLIER
        value: "{{workflow.parameters.data_multiplier}}"
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: train-data
    container:
      command: [python3, train.py]
      image: train-data
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
      - name: DATA_MULTIPLIER
        value: "{{workflow.parameters.data_multiplier}}"
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
