apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: machine-learning-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0, pipelines.kubeflow.org/pipeline_compilation_time: '2023-10-09T16:33:59.363121',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example pipeline that
      trains and logs a regression model.", "inputs": [{"name": "data_multiplier",
      "type": "Integer"}], "name": "Machine Learning Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0}
spec:
  entrypoint: machine-learning-pipeline
  templates:
  - name: machine-learning-pipeline
    inputs:
      parameters:
      - {name: data_multiplier}
    dag:
      tasks:
      - name: preprocess-data
        template: preprocess-data
        arguments:
          parameters:
          - {name: data_multiplier, value: '{{inputs.parameters.data_multiplier}}'}
      - name: test-data
        template: test-data
        dependencies: [train-data]
      - name: train-data
        template: train-data
        dependencies: [preprocess-data]
  - name: preprocess-data
    container:
      args: ['--data_multiplier={{inputs.parameters.data_multiplier}}']
      command: [python3, preprocess.py]
      image: preprocess-data
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    inputs:
      parameters:
      - {name: data_multiplier}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: test-data
    container:
      command: [python3, test.py]
      image: test-data
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: train-data
    container:
      command: [python3, train.py]
      image: train-data
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  arguments:
    parameters:
    - {name: data_multiplier}
  serviceAccountName: pipeline-runner
