apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vineyard-operator.fullname" . }}-manager-role
  labels:
  {{- include "vineyard-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - globalobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - globalobjects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - localobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - localobjects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - operations/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - operations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - recovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - recovers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - sidecars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - sidecars/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - sidecars/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardds/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.v6d.io
  resources:
  - vineyardds/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vineyard-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "vineyard-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "vineyard-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'