apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "vineyard-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "vineyard-operator.fullname" . }}-serving-cert
  labels:
  {{- include "vineyard-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vineyard-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-k8s-v6d-io-v1alpha1-globalobject
  failurePolicy: Fail
  name: vglobalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - globalobjects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vineyard-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-k8s-v6d-io-v1alpha1-localobject
  failurePolicy: Fail
  name: vlocalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - localobjects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vineyard-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-k8s-v6d-io-v1alpha1-operation
  failurePolicy: Fail
  name: voperation.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vineyard-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-k8s-v6d-io-v1alpha1-vineyardd
  failurePolicy: Fail
  name: vvineyardd.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vineyardds
  sideEffects: None