# referred from https://github.com/etcd-io/etcd/blob/master/hack/kubernetes-deploy/etcd.yml

{{- $etcd := getEtcdConfig }}
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd {{- $etcd.Rank }}
  #annotations:
  #  app: etcd
  name: etcd {{- $etcd.Rank }}
  namespace: {{ $etcd.Namespace }}
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcd {{- $etcd.Rank}}
    - --initial-advertise-peer-urls
    - http://etcd{{- $etcd.Rank -}} :2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd{{- $etcd.Rank}}:2379
    - --initial-cluster
    - {{ $etcd.Endpoints }}
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:v3.4.16
    name: etcd
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Always