# referred from https://github.com/etcd-io/etcd/blob/master/hack/kubernetes-deploy/etcd.yml

{{- $etcd := getEtcdConfig }}
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd {{- $etcd.Rank }}
  name: etcd {{- $etcd.Rank }}
  namespace: {{ $etcd.Namespace }}
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd {{- $etcd.Rank }}
