apiVersion: v1
kind: Pod
metadata:
  name: injection-containers
# we only get the following containers
spec:
  containers:
    - name: vineyard-sidecar
      image: {{ .Spec.Vineyard.Image }}
      imagePullPolicy: {{ .Spec.Vineyard.ImagePullPolicy }}
      env:
      - name: VINEYARDD_UID
        value: {{ .UID }}
      - name: VINEYARDD_NAME
        value: {{ .Name }}
      - name: VINEYARDD_NAMESPACE
        value: {{ .Namespace }}
      command:
      - /bin/bash
      - -c
      - >
        /usr/bin/wait-for-it.sh -t 60 etcd-for-vineyard.{{ .Namespace }}.svc.cluster.local:2379;
        sleep 1;
        /usr/local/bin/vineyardd
        --sync_crds {{ .Spec.Vineyard.SyncCRDs }}
        --socket /var/run/vineyard.sock
        --size {{ .Spec.Vineyard.Size }}
        --stream_threshold {{ .Spec.Vineyard.StreamThreshold }}
        --etcd_cmd etcd
        --etcd_prefix /vineyard
        --etcd_endpoint http://etcd-for-vineyard:2379
        {{- if .Spec.Vineyard.Spill.Path }}
        --spill_path {{ .Spec.Vineyard.Spill.Path }}
        --spill_lower_rate {{ .Spec.Vineyard.Spill.SpillLowerRate }}
        --spill_upper_rate {{ .Spec.Vineyard.Spill.SpillUpperRate }}
        {{- end }}
        {{- if .Spec.Metric.Enable }}
        --metrics
        -log_dir /var/log/vineyard/
        {{- end }}
      ports:
      - containerPort: 9600
        name: vineyard-rpc
        protocol: TCP
      volumeMounts:
      - name: vineyard-socket
      {{- if .Spec.Volume.MountPath }}
        mountPath: {{ .Spec.Volume.MountPath }}
      {{- else }}
        mountPath: /var/run
      {{- end }}
    {{- if .Spec.Metric.Enable }}
    - name: metrics
      image : {{ .Spec.Metric.Image }}
      imagePullPolicy: {{ .Spec.Metric.ImagePullPolicy }}
      command: ["./grok_exporter"]
      args: ["-config", "grok_exporter.yml", "-disable-exporter-metrics", "&"]
      ports:
        - name: exporter
          containerPort: 9144
          protocol: TCP
      volumeMounts:
      - name: log
        mountPath: /var/log/vineyard
    {{- end }}
  volumes:
  - name: vineyard-socket
  {{- if .Spec.Volume.PvcName }}
    persistentVolumeClaim:
      claimName: {{ .Spec.Volume.PvcName }}
  {{- else }}
    emptyDir: {}
  {{- end }}
  {{- if .Spec.Metric.Enable }}
  - name: log
    emptyDir: {}
  {{- end }}
