---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-v6d-io-v1alpha1-globalobject
  failurePolicy: Fail
  name: mglobalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - globalobjects
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-v6d-io-v1alpha1-localobject
  failurePolicy: Fail
  name: mlocalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - localobjects
  sideEffects: NoneOnDryRun
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-v6d-io-v1alpha1-globalobject
  failurePolicy: Fail
  name: vglobalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - globalobjects
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-v6d-io-v1alpha1-localobject
  failurePolicy: Fail
  name: vlocalobject.kb.io
  rules:
  - apiGroups:
    - k8s.v6d.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - localobjects
  sideEffects: NoneOnDryRun
