# Copyright 2020-2022 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/version: {{ .Spec.Version }}
    app.kubernetes.io/instance: vineyardd
    app.kubernetes.io/component: deployment
spec:
  replicas: {{ .Spec.Replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Name }}
      app.kubernetes.io/instance: vineyardd
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/version: {{ .Spec.Version }}
        app.kubernetes.io/instance: vineyardd
        app.kubernetes.io/component: deployment
    spec:
      serviceAccountName: {{ .Name }}
      containers:
        - name: vineyardd
          image: {{ .Spec.Image }}
          {{ if .Spec.ImagePullPolicy }}  
          imagePullPolicy: {{ .Spec.ImagePullPolicy }}
          {{ else }}
          imagePullPolicy: IfNotPresent
          {{ end }}
          command:
          - /bin/bash
          - -c
          - >
            /usr/bin/wait-for-it.sh -t 60 etcd-for-vineyard.{{ .Namespace }}.svc.cluster.local:2379;
            sleep 1;
            /usr/local/bin/vineyardd
            {{- if .Spec.Config.EtcdCmd }}
            --etcd_cmd {{ .Spec.Config.EtcdCmd }}
            {{- end }}
            {{- if .Spec.Config.EtcdPrefix }}
            --etcd_prefix {{ .Spec.Config.EtcdPrefix }}
            {{- end }}
            {{- if .Spec.Config.EnablePrometheus }}
            --prometheus {{ .Spec.Config.EnablePrometheus }}
            {{- end }}
            {{- if .Spec.Config.Socket }}
            --socket {{ .Spec.Config.Socket }}
            {{- end }}
            {{- if .Spec.Config.SpillConfig.Path }}
            --spill_path {{ .Spec.Config.SpillConfig.Path }}
            {{- end }}
            {{- if .Spec.Config.SpillConfig.SpillLowerRate }}
            --spill_lower_rate {{ .Spec.Config.SpillConfig.SpillLowerRate }}
            {{- end }}
            {{- if .Spec.Config.SpillConfig.SpillUpperRate }}
            --spill_upper_rate {{ .Spec.Config.SpillConfig.SpillUpperRate }}
            {{- end }}
            {{- if .Spec.Config.StreamThreshold }}
            --stream_threshold {{ .Spec.Config.StreamThreshold }}
            {{- end }}
            {{- if .Spec.Config.SharedMemorySize }}
            --size {{ .Spec.Config.SharedMemorySize }} 
            {{- end }}
            {{- if .Spec.Config.EnableMetrics }}
            --metrics -log_dir /var/log/vineyard/
            {{- end }} 
            {{- if .Spec.Config.EtcdEndpoint }}
            --etcd_endpoint {{ .Spec.Config.EtcdEndpoint }}
            {{ else}}
            --etcd_endpoint http://etcd-for-vineyard.{{ .Namespace }}.svc.cluster.local:2379
            {{- end }}
            {{- if .Spec.Config.SyncCRDs }}
            --sync_crds {{ .Spec.Config.SyncCRDs }}
            {{- end }}
          env:
            - name: VINEYARDD_UID
              value: {{ .UID }}
            - name: VINEYARDD_NAME
              value: {{ .Name }}
            - name: VINEYARDD_NAMESPACE
              value: {{ .Namespace }}
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: USER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{range .Spec.Env}}
            - name: {{ .Name }}
              value: {{ .Value }}
            {{end}}
          ports:
            - name: rpc
              containerPort: 9600
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9600
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
              - ls
              - /var/run/vineyard.sock
          volumeMounts:
            - name: run
              mountPath: /var/run
            {{- if .Spec.Config.SpillConfig.Name }}
            - name: {{ .Spec.Config.SpillConfig.Name }}
              mountPath: {{ .Spec.Config.SpillConfig.Path }}
            {{- end }}
            - name: shm
              mountPath: /dev/shm
            - name: log
              mountPath: /var/log/vineyard
        {{- if .Spec.Metric.Image }}
        - name: metrics
          image : {{ .Spec.Metric.Image }}:latest
          imagePullPolicy: {{ .Spec.Metric.ImagePullPolicy }}
          command: ["./grok_exporter"]
          args: ["-config", "grok_exporter.yml", "-disable-exporter-metrics", "&"]
          ports:
            - name: exporter
              containerPort: 9144
              protocol: TCP
          volumeMounts:
          - name: log
            mountPath: /var/log/vineyard
        {{- end }}   
      volumes:
      - name: run
        hostPath:
          {{- if .Spec.Config.Socket }}
          path: {{ .Spec.Config.Socket }}
          {{ else }}
          path: /var/run/vineyard-{{ .Namespace }}-{{ .Name }}
          {{- end }}
      {{- if .Spec.Config.SpillConfig.Name }}
      - name: {{ .Spec.Config.SpillConfig.Name }}
        persistentVolumeClaim:
          claimName: {{ .Spec.Config.SpillConfig.Name }}
      {{- end }}
      - name: shm
        emptyDir:
          medium: Memory
      - name: log
        emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                     - vineyardd
              topologyKey: "kubernetes.io/hostname"  