# Copyright 2020-2022 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Spec.Config.SpillConfig.Name }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Spec.Config.SpillConfig.Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Spec.Config.SpillConfig.Name }}
    app.kubernetes.io/version: {{ .Spec.Version }}
    app.kubernetes.io/instance: vineyardd
    app.kubernetes.io/component: PersistentVolume
spec:
  {{- if .Spec.Config.SpillConfig.PersistentVolumeSpec }}
  {{ $spec := .Spec.Config.SpillConfig.PersistentVolumeSpec }}
  {{- if $spec.AccessModes }}
  accessModes:
    {{- range $spec.AccessModes }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if $spec.Capacity }}
  capacity:
    {{- range $key, $value := $spec.Capacity }}
    {{ $key }}: {{ getStorage $value }}
    {{- end }}
  {{- end }}
  {{- if $spec.HostPath }}
  hostPath:
    {{- if $spec.HostPath.Path }}
    path: {{ $spec.HostPath.Path }}
    {{- end }}
    {{- if $spec.HostPath.Type }}
    type: {{ $spec.HostPath.Type }}
    {{- end }}
  {{- end }}
  {{- if $spec.NFS }}
  nfs:
    {{- if $spec.NFS.Path }}
    path: {{ $spec.NFS.Path }}
    {{- end }}
    {{- if $spec.NFS.Server }}
    server: {{ $spec.NFS.Server }}
    {{- end }}
    {{- if $spec.NFS.ReadOnly }}
    readOnly: {{ $spec.NFS.ReadOnly }}
    {{- end }}
  {{- end }}
  {{- if $spec.StorageClassName }}
  storageClassName: {{ $spec.StorageClassName }}
  {{- end }}
  {{- if $spec.VolumeMode }}
  volumeMode: {{ $spec.VolumeMode }}
  {{- end }}
  {{- end }}
{{ end }}