# Copyright 2020-2023 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Packages for Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-vineyardd:
    runs-on: ${{ matrix.os }}
    if: ${{ github.repository == 'v6d-io/v6d' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login docker registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build vineyardd on Linux
        run: |
          sudo docker build . -f docker/Dockerfile.vineyardd -t ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }}
          sudo docker run --rm -v `pwd`:/target ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} sh -c "cp /usr/local/bin/vineyardd /target/"
          ldd ./vineyardd

      - name: Package vineyardd artifact on Linux
        run: |
          sha512sum ./vineyardd > vineyardd.${{ github.sha }}.sha512sum
          echo "Checksum is: "
          cat ./*.sha512sum
          tar zcvfh vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz ./vineyardd vineyardd.${{ github.sha }}.sha512sum

      - name: Upload docker image as nightly
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'v6d-io/v6d' }}
        run: |
          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:alpine-nightly
          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:nightly

          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }}
          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:alpine-nightly
          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:nightly

      - name: Extract tag name
        id: tag
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Tag and upload docker for releases
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        run: |
          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ steps.tag.outputs.TAG }}
          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:${{ steps.tag.outputs.TAG }}

          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ steps.tag.outputs.TAG }}
          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:${{ steps.tag.outputs.TAG }}

          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:alpine-latest
          sudo docker tag ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }} \
                          ghcr.io/v6d-io/v6d/vineyardd:latest

          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:alpine-${{ github.sha }}
          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:alpine-latest
          sudo docker push ghcr.io/v6d-io/v6d/vineyardd:latest

      - name: Upload vineyardd to tagged release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          asset_name: vineyardd-${{ steps.tag.outputs.TAG }}-linux_x86-64.tar.gz
          tag: ${{ steps.tag.outputs.TAG }}
          prerelease: false
          overwrite: true
          body: "vineyard ${{ steps.tag.outputs.TAG }}"

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          path: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz

  build-vineyardctl:
    runs-on: ${{ matrix.os }}
    if: ${{ github.repository == 'v6d-io/v6d' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      
      - name: Build vineyardctl
        run: |
          go build -a -o vineyardctl k8s/cmd/main.go
      
      - name: Upload CI artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vineyardctl.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          path: vineyardctl.${{ runner.os }}-generic.${{ github.sha }}.tar.gz

  build-wheels:
    needs: [build-vineyardd,build-vineyardctl]
    runs-on: ${{ matrix.os }}
    if: ${{ github.repository == 'v6d-io/v6d' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310, cp311-cp311]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate Summary for Submodules
        run: |
          git submodule > git-modules.txt
          cat git-modules.txt

      - name: Cache for cccahe
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ matrix.os }}-${{ matrix.python }}-ccache-${{ hashFiles('**/git-modules.txt') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python }}-ccache-

      - name: Download vineyardd artifacts
        uses: actions/download-artifact@v3
        with:
          name: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz

      - name: Prepare vineyardd binary
        run: |
          tar zxvf vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          mv vineyardd python/vineyard/vineyardd
      
      - name: Download vineyardctl artifacts
        uses: actions/download-artifact@v3
        with:
          name: vineyardctl.${{ runner.os }}-generic.${{ github.sha }}.tar.gz

      - name: Prepare vineyardctl binary
        run: |
          tar zxvf vineyardctl.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          mv vineyardctl python/vineyard/vineyardctl

      - name: Login docker registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build wheel package on Linux
        run: |
          if [[ "${{ matrix.python }}" == "cp311-cp311" ]];
          then
            export base=manylinux2014:20230115
          else
            export base=manylinux1:20220512
          fi

          sudo docker build . -f docker/pypa/Dockerfile.manylinux1-wheel \
                              -t ghcr.io/v6d-io/v6d/vineyard-wheel:${{ matrix.python }}.${{ github.sha }} \
                              --build-arg BASE=$base \
                              --build-arg python=${{ matrix.python }}
          sudo docker run --rm -v `pwd`:/target ghcr.io/v6d-io/v6d/vineyard-wheel:${{ matrix.python }}.${{ github.sha }} sh -c "cp -r /work/fixed_wheels/ /target/"
          ls -la ./fixed_wheels/

      - name: Extract tag name
        id: tag
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload wheels to tagged release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fixed_wheels/*.whl
          file_glob: true
          tag: ${{ steps.tag.outputs.TAG }}
          prerelease: false
          overwrite: true
          body: "vineyard ${{ steps.tag.outputs.TAG }}"

      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.repository == 'v6d-io/v6d' }}
        with:
          name: vineyard-linux-wheels-${{ matrix.python }}
          path: fixed_wheels/*.whl
