# Copyright 2020-2022 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Kubernetes Operator

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'k8s/**'
  pull_request:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'k8s/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      IMG: docker.pkg.github.com/v6d-io/v6d/vineyard-controller
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'

      - name: Golang format and lint
        run: |
          cd k8s
          make golint
          if [ $? -ne ]; then
              echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
              echo "| golangci-lint (golang format) failures found!"
              echo "|"
              echo "|    ${GOPATH}/bin/golangci-lint run ./... --fix"
              echo "|"
              echo "| to fix this error."
              echo "|"
              echo "| The tool golangci-lint can be installed by"
              echo "|"
              echo "|    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
              echo "|"
              echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
              exit -1
          fi

      - name: Operator
        run: |
          cd k8s
          make

      - name: Login docker registry
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

      - name: Docker images
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        run: |
          cd k8s
          sudo make docker-build IMG=${IMG}:${{ github.sha }}
          sudo docker tag ${IMG}:${{ github.sha }} ${IMG}:nightly

      - name: Publish docker images
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'v6d-io/v6d' }}
        run: |
          cd k8s
          sudo make docker-push IMG=${IMG}:${{ github.sha }}
          sudo docker push ${IMG}:nightly
